name: print created env
on: workflow_dispatch
env: 
    secret: $secrets.GOOD_SECRET
jobs:
    mainjob:
        name: print env
        runs-on: ubuntu-latest
        steps:
            - run: echo $secret