name: workflow-1
on: 
    workflow_dispatch

env:
    name: mani
    test: tested
jobs:
  my-job:
    name: crazy job
    runs-on: ubuntu-latest
    env: 
        gen: M
        test: v1

    steps:
      - name: ne job
        run: echo "Hola"  
      - name: print env vars
        run: |
            echo "Name is $name"
            echo "Age is $age"
            echo "Gender is $gen"
            echo "test $test"
            echo "test ${{env.test}}"
        env:
            age : 21
