name: Workflow with environment
on: workflow_dispatch
jobs:
    job1:
        name: mani job
        runs-on: windows-latest
        environment: 
            name: deploy
            url: https://google.com
        steps:
            - name: Get secret from enivornment
              run: echo " Secret:${secrets.Good_Secret}"
              