name: print created env
on: workflow_dispatch
env: 
    secret: ${{secrets.GOOD_SECRET}}
jobs:
    mainjob:
        runs-on: ubuntu-latest
        steps:
            - name: print env
              run: echo "$secret"

            - name: another env
              run: |
                echo: echo "$secret"
                echo: echo "${{secrets.GOOD_SECRET}}"
        