name: upload and download artifacts
on: workflow_dispatch
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: upload artifact 
              run: echo "This is text" >mani.txt

            - uses: actions/upload-artifact@v4
              with:
                name: file
                path: mani.txt
    job2:
        runs-on: ubuntu-latest
        needs: job1
        steps:
        
            
            - uses: actions/download-artifact
              with:
                name: file
            - run: cat mani.txt